-- Cava+ Orça V1.1 — execute uma vez num projeto Supabase novo.
-- Signup cria empresa, owner e settings via trigger transacional (sem service key no browser).
create extension if not exists pgcrypto;
create type public.project_status as enum ('Rascunho','Em análise','Em revisão','Finalizado');
create type public.quantity_status as enum ('Confirmado','Estimado','Necessita revisão');

create table public.companies(id uuid primary key default gen_random_uuid(),name text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.company_members(company_id uuid not null references public.companies on delete cascade,user_id uuid not null references auth.users on delete cascade,role text not null default 'member' check(role in ('owner','admin','member')),created_at timestamptz not null default now(),primary key(company_id,user_id));
create table public.settings(id uuid primary key default gen_random_uuid(),company_id uuid not null unique references public.companies on delete cascade,bdi_percent numeric(8,4) not null default 22 check(bdi_percent>=0),currency text not null default 'BRL',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id));
create table public.projects(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies on delete cascade,name text not null,client text not null,address text,city text,state text,project_type text not null default 'Residencial' check(project_type in ('Residencial','Comercial','Reforma','Outro')),area numeric(14,2) not null default 0 check(area>=0),floors integer not null default 1 check(floors>0),standard text not null default 'Médio' check(standard in ('Econômico','Médio','Alto','Personalizado')),notes text,status public.project_status not null default 'Rascunho',created_by uuid references auth.users on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id));
create table public.project_documents(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,storage_path text not null,file_name text not null,mime_type text not null default 'application/pdf' check(mime_type='application/pdf'),size_bytes bigint check(size_bytes between 1 and 20971520),version integer not null default 1,uploaded_by uuid references auth.users on delete set null,created_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade);
create table public.project_analysis(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,document_id uuid,status text not null default 'pending' check(status in ('pending','processing','completed','failed')),provider text not null default 'demo',result jsonb not null default '{}'::jsonb,error_message text,started_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade,foreign key(company_id,document_id) references public.project_documents(company_id,id) on delete set null (document_id));
create table public.project_rooms(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,name text not null,area numeric(14,2),source_document_id uuid,source_page integer,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade,foreign key(company_id,source_document_id) references public.project_documents(company_id,id) on delete set null (source_document_id));
create table public.project_elements(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,room_id uuid,name text not null,element_type text,properties jsonb not null default '{}'::jsonb,source_document_id uuid,source_page integer,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade,foreign key(company_id,room_id) references public.project_rooms(company_id,id) on delete set null (room_id),foreign key(company_id,source_document_id) references public.project_documents(company_id,id) on delete set null (source_document_id));
create table public.quantities(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,element_id uuid,category text not null,description text not null,unit text not null check(unit in ('m','m²','m³','kg','un','l','h')),quantity numeric(14,4) not null default 0 check(quantity>=0),loss_percent numeric(8,4) not null default 0 check(loss_percent>=0),final_quantity numeric(14,4) generated always as(quantity*(1+loss_percent/100)) stored,status public.quantity_status not null default 'Necessita revisão',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade,foreign key(company_id,element_id) references public.project_elements(company_id,id) on delete set null (element_id));
create table public.quantity_sources(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,quantity_id uuid not null,document_id uuid,room_id uuid,element_id uuid,page integer,room_label text,element_label text,observation text,calculation_method text,created_at timestamptz not null default now(),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade,foreign key(company_id,quantity_id) references public.quantities(company_id,id) on delete cascade,foreign key(company_id,document_id) references public.project_documents(company_id,id) on delete set null (document_id),foreign key(company_id,room_id) references public.project_rooms(company_id,id) on delete set null (room_id),foreign key(company_id,element_id) references public.project_elements(company_id,id) on delete set null (element_id));
create table public.compositions(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies on delete cascade,code text not null,description text not null,unit text not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,code));
create table public.price_items(id uuid primary key default gen_random_uuid(),company_id uuid not null references public.companies on delete cascade,code text not null,description text not null,category text not null,unit text not null,unit_price numeric(14,4) not null default 0 check(unit_price>=0),supplier text,region text,source text,price_date date not null default current_date,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,code));
create table public.composition_items(id uuid primary key default gen_random_uuid(),company_id uuid not null,composition_id uuid not null,price_item_id uuid,description text not null,coefficient numeric(14,6) not null check(coefficient>=0),unit_price numeric(14,4) not null check(unit_price>=0),position integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(company_id,composition_id) references public.compositions(company_id,id) on delete cascade,foreign key(company_id,price_item_id) references public.price_items(company_id,id) on delete set null (price_item_id));
create table public.budgets(id uuid primary key default gen_random_uuid(),company_id uuid not null,project_id uuid not null,name text not null default 'Orçamento principal',status text not null default 'draft' check(status in ('draft','review','finalized')),bdi_percent numeric(8,4) not null default 0 check(bdi_percent>=0),created_by uuid references auth.users on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),unique(company_id,project_id),foreign key(company_id,project_id) references public.projects(company_id,id) on delete cascade);
create table public.budget_groups(id uuid primary key default gen_random_uuid(),company_id uuid not null,budget_id uuid not null,name text not null,position integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(company_id,id),foreign key(company_id,budget_id) references public.budgets(company_id,id) on delete cascade);
create table public.budget_items(id uuid primary key default gen_random_uuid(),company_id uuid not null,budget_id uuid not null,group_id uuid,quantity_id uuid,composition_id uuid,code text,description text not null,unit text not null,quantity numeric(14,4) not null check(quantity>=0),unit_price numeric(14,4) not null check(unit_price>=0),position integer not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),foreign key(company_id,budget_id) references public.budgets(company_id,id) on delete cascade,foreign key(company_id,group_id) references public.budget_groups(company_id,id) on delete set null (group_id),foreign key(company_id,quantity_id) references public.quantities(company_id,id) on delete set null (quantity_id),foreign key(company_id,composition_id) references public.compositions(company_id,id) on delete set null (composition_id));

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path=pg_catalog as $$ begin new.updated_at=now(); return new; end $$;
do $$ declare t text; begin foreach t in array array['companies','settings','projects','project_analysis','project_rooms','project_elements','quantities','compositions','price_items','composition_items','budgets','budget_groups','budget_items'] loop execute format('create trigger %I before update on public.%I for each row execute function public.set_updated_at()',t||'_set_updated_at',t); end loop; end $$;

create or replace function public.is_company_member(target_company uuid) returns boolean language sql stable security definer set search_path=public,pg_temp as $$ select exists(select 1 from public.company_members m where m.company_id=target_company and m.user_id=(select auth.uid())) $$;
revoke all on function public.is_company_member(uuid) from public,anon;
grant execute on function public.is_company_member(uuid) to authenticated;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public,auth,pg_temp as $$
declare new_company uuid; company_label text;
begin
  company_label := nullif(trim(coalesce(new.raw_user_meta_data->>'company_name','')),'');
  if company_label is null then company_label := coalesce(nullif(split_part(new.email,'@',1),''),'Minha empresa'); end if;
  insert into public.companies(name) values(company_label) returning id into new_company;
  insert into public.company_members(company_id,user_id,role) values(new_company,new.id,'owner');
  insert into public.settings(company_id) values(new_company);
  return new;
end $$;
revoke all on function public.handle_new_user() from public,anon,authenticated;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.companies enable row level security;
alter table public.company_members enable row level security;
create policy companies_member_select on public.companies for select to authenticated using(public.is_company_member(id));
create policy companies_member_update on public.companies for update to authenticated using(public.is_company_member(id)) with check(public.is_company_member(id));
create policy memberships_read_own_company on public.company_members for select to authenticated using(public.is_company_member(company_id));
do $$ declare t text; begin foreach t in array array['settings','projects','project_documents','project_analysis','project_rooms','project_elements','quantities','quantity_sources','compositions','price_items','composition_items','budgets','budget_groups','budget_items'] loop
 execute format('alter table public.%I enable row level security',t);
 execute format('create policy %I on public.%I for all to authenticated using(public.is_company_member(company_id)) with check(public.is_company_member(company_id))',t||'_tenant_access',t);
end loop; end $$;
grant usage on schema public to authenticated;
grant select,insert,update,delete on public.companies,public.company_members,public.settings,public.projects,public.project_documents,public.project_analysis,public.project_rooms,public.project_elements,public.quantities,public.quantity_sources,public.compositions,public.price_items,public.composition_items,public.budgets,public.budget_groups,public.budget_items to authenticated;
revoke all on all tables in schema public from anon;

create index projects_company_updated on public.projects(company_id,updated_at desc);
create index documents_company_project on public.project_documents(company_id,project_id,created_at desc);
create index quantities_company_project on public.quantities(company_id,project_id);
create index budgets_company_project on public.budgets(company_id,project_id);
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('project-documents','project-documents',false,20971520,array['application/pdf']) on conflict(id) do update set public=false,file_size_limit=20971520,allowed_mime_types=array['application/pdf'];
drop policy if exists project_documents_select on storage.objects;
drop policy if exists project_documents_insert on storage.objects;
drop policy if exists project_documents_delete on storage.objects;
create policy private_project_pdf_select on storage.objects for select to authenticated using(bucket_id='project-documents' and (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and public.is_company_member(((storage.foldername(name))[1])::uuid) and exists(select 1 from public.projects p where p.company_id=((storage.foldername(name))[1])::uuid and p.id=((storage.foldername(name))[2])::uuid));
create policy private_project_pdf_insert on storage.objects for insert to authenticated with check(bucket_id='project-documents' and (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and public.is_company_member(((storage.foldername(name))[1])::uuid) and exists(select 1 from public.projects p where p.company_id=((storage.foldername(name))[1])::uuid and p.id=((storage.foldername(name))[2])::uuid));
create policy private_project_pdf_update on storage.objects for update to authenticated using(bucket_id='project-documents' and public.is_company_member(((storage.foldername(name))[1])::uuid) and exists(select 1 from public.projects p where p.company_id=((storage.foldername(name))[1])::uuid and p.id=((storage.foldername(name))[2])::uuid)) with check(bucket_id='project-documents' and public.is_company_member(((storage.foldername(name))[1])::uuid) and exists(select 1 from public.projects p where p.company_id=((storage.foldername(name))[1])::uuid and p.id=((storage.foldername(name))[2])::uuid));
create policy private_project_pdf_delete on storage.objects for delete to authenticated using(bucket_id='project-documents' and (storage.foldername(name))[1] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and (storage.foldername(name))[2] ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$' and public.is_company_member(((storage.foldername(name))[1])::uuid) and exists(select 1 from public.projects p where p.company_id=((storage.foldername(name))[1])::uuid and p.id=((storage.foldername(name))[2])::uuid));
